version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/we-go?autoReconnect=true&createDatabaseIfNotExist=true
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: we-go
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
